export function statusArray() {
  let sArray: any = {
    allocated: 'Sipariş Hazırlanmaya Başlandı',
    closed: 'İade-Para İadesi Yapıldı',
    waiting: 'Başarız Sipariş-Para iadesi yapılacak',
    holded: 'Başarız Sipariş-Para İadesi Yapılacak',
    mp_fraud: 'Ödeme Riski Sebebiyle İptal Edildi',
    mp_holded: 'Başarız Sipariş-Para İadesi Yapılacak',
    mp_pending: 'Ödeme Bekleniyor',
    mp_waiting: 'Başarız Sipariş-Para iadesi yapılacak',
    mp_change_delivered: 'Değişim-Satıcıya Teslim',
    change_shipped: 'Değişim-Ürün Kargoya Verildi',
    mp_change_shipped: 'Değişim-Ürün Kargoya Verildi',
    change_requested: 'Değişim Kodu Alındı',
    mp_change_requested: 'Değişim Kodu Alındı',
    change_request_processing: 'Değişim-Talep İnceleniyor',
    change_request_approved: 'Değişim Talebi Onaylandı',
    mp_change_request_approved: 'Değişim Talebi Onaylandı',
    change_delivered: 'Değişim-Depoya Teslim',
    order_canceled: 'İptal-Tedarik Edilemedi',
    UnSupplied: 'İptal-Tedarik Edilemedi',
    warehouse_notified: 'Sipariş Hazırlanması için Depoya İletildi',
    invoiced: 'Faturası Hazırlandı',
    fraud: 'Ödeme Riski Sebebiyle İptal Edildi',
    delivered: 'Depoya Dönen Sipariş',
    mp_allocated: 'Sipariş Hazırlanmaya Başlandı',
    pending: 'Ödeme Bekleniyor',
    mp_processing: 'Sipariş Alındı',
    processing: 'Sipariş Alındı',
    mp_warehouse_notified: 'Sipariş Hazırlanması için Satıcıya İletildi',
    refund_delivered: 'İade Depoya Teslim Edildi İnceleniyor',
    waiting_refund: 'İade-Para İadesi Bekleniyor',
    mp_refund_delivered: 'İade Depoya Teslim Edildi İnceleniyor',
    refund_shipped: 'İade Ürün Kargoda',
    refund_rejected: 'İade Reddedildi',
    mp_refund_requested: 'İade Kodu Alındı',
    refund_requested: 'İade Kodu Alındı',
    mp_refund_shipped: 'İade Ürün Kargoda',
    mp_refund_rejected: 'İade Reddedildi',
    mp_change_request_processing: 'Değişim-Talep İnceleniyor',
    canceled: 'İptal Edildi',
    mp_canceled: 'İptal Edildi',
    mp_order_canceled: 'İptal-Tedarik Edilemedi',
    waiting_cancel: 'İptal-Para İadesi Bekleniyor',
    moving: 'Kargo Dağıtıma Çıktı',
    'mp_moving	': 'Kargo Dağıtıma Çıktı',
    'arrived	': 'Kargo Teslimat Şubesine Ulaştı',
    'mp_arrived	': 'Kargo Teslimat Şubesine Ulaştı',
    mp_transfer: 'Kargo Teslimat Şubesine Gidiyor',
    transfer: 'Kargo Teslimat Şubesine Gidiyor',
    mp_refund_rejected_shipped: 'İade-Reddedildi Ürün Müşteriye Gönderildi',
    mp_invoiced: 'Faturası Hazırlandı',
    mp_packaged: 'Ürün Paketlendi',
    kargoya_hazir: 'Sipariş Kargoya Hazır',
    mp_kargoya_hazir: 'Sipariş Kargoya Hazır',
    mp_waiting_shipment: 'Sipariş Kargoya Hazır',
    waiting_shipment: 'Sipariş Kargoya Hazır',
    'mp_shipped	': 'Kargoya Verildi',
    'shipped	': 'Kargoya Verildi',
    mp_store_arrived: 'Mağazaya Teslim Edildi',
    store_arrived: 'Mağazaya Teslim Edildi',
    magazada: 'Ürün Mağazaya Teslim Edildi',
    mp_magazada: 'Ürün Mağazaya Teslim Edildi',
    mp_store_collect: 'Ürün Mağazaya Teslim Edildi',
    store_collect: 'Ürün Mağazaya Teslim Edildi',
    store_complete: 'Mağazadan Müşteriye Teslim Edildi',
    mp_store_complete: 'Mağazadan Müşteriye Teslim Edildi',
    mp_refund_returned: 'İade Reddedildi Ürün Müşteriye Teslim Edildi',
    refund_returned: 'İade Reddedildi Ürün Müşteriye Teslim Edildi',
    complete: 'Müşteriye Teslim Edildi',
    teslim_edildi: 'Müşteriye Teslim Edildi',
    undelivered: 'Kargoda-Müşteriye Teslim Edilemedi',
    teslim_alinmadi: 'Ürün Kargoda-Teslim Edilemedi',
    mp_payment_review: 'Ödeme Bekleniyor',
    payment_review: 'Ödeme Bekleniyor',
    mp_pending_payment: 'Ödeme Bekleniyor',
    pending_payment: 'Ödeme Bekleniyor',
    mp_payment_cancel: 'İptal-Ödeme Alınamadı',
    payment_cancel: 'İptal-Ödeme Alınamadı',
    packaged: 'Ürün Paketlendi',
    mp_waiting_cancel: 'İptal-Para İadesi Bekleniyor',
    mp_waiting_refund: 'İade-Para İadesi Bekleniyor',
    refunded: 'İade-Para İadesi Yapıldı',
    mp_closed: '	İade-Para İadesi Yapıldı',
    mp_refunded: '	İade-Para İadesi Yapıldı',
    refund_rejected_shipped: 'İade-Reddedildi Ürün Müşteriye Gönderildi',
    mp_UnSupplied: 'İptal-Tedarik Edilemedi',
    mp_complete: 'Müşteriye Teslim Edildi',
    mp_delivered: 'Satıcıya Dönen Sipariş',
    mp_teslim_edildi: 'Müşteriye Teslim Edildi',
    mp_undelivered: 'Kargoda-Müşteriye Teslim Edilemedi',
    mp_teslim_alinmadi: 'Ürün Kargoda-Teslim Edilemedi',
    mp_shipment_lost: 'Kargoda Kaybolan Sipariş-Para İadesi Yapılacak',
    shipment_lost: 'Kargoda Kaybolan Sipariş-Para İadesi Yapılacak',
    Hold: 'Tedariği Gecikecek Sipariş',
    ItemStatus: 'Müşteri Temsilcisinin Göreceği Statüler',
    hatali_varis_subesinde: 'Sipariş Yeni Teslim Şubesine Yönlendirildi',
    yeni_varis_subesine_yolda: 'Sipariş Yeni Teslim Birimine Doğru Yolda',
    yeni_varis_subesinde: 'Sipariş Yeni Teslim Biriminde',
    yeniden_dagitimda:
      'Sipariş Yeni Teslim Biriminden Teslim Edilmek Üzere Dağıtıma Çıkarıldı',
    iade_subesinde: 'Sipariş Teslim Edilemedi Depoya İade Edilecek',
    red_kargo_yolda: 'Sipariş Depoya İade Edilmek Üzere Yolda',
    red_kargo_varis_biriminde:
      'Sipariş Depoya İade Edilmek Üzere Teslim Biriminde',
    red_kargo_depoya_dagitimda: 'Sipariş Depoya İade Edilmek Üzere Dağıtımda',
    'refund_arrived İade-Depoya': 'Teslim Edildi İnceleniyor',
    change_rejected: 'Değişim Talebi Reddildi',
    change_rejected_shipped: 'Değişim - Red Ürün Müşteriye Kargolandı',
    change_arrived: 'Değişim - Teslimat Şubesine Ulaştı',
    change_returned: 'Değişim - Ürün Müşteriye İade Edildi',
    'changed Değişim': 'Gerçekleşti',
    freeze: 'Duraklatıldı - İnceleniyor',
  };

  return sArray;
}

export function GetCrmOrderItemStaus(params: string) {
  var status = statusArray();
  var value = status[params];
  return value;
}
