export const NavigationTree = [
  {
    keywords: ["crm", "şikayet", "sikayet", "magaza", "anasayfa"],
    path: "Crm",
    screen: "MainScreen",
    params: {},
    title: "Anasayfa -> CRM -> Şikayet Yönetimi",
  },
  {
    keywords: [
      "crm",
      "şikayet",
      "sikayet",
      "magaza",
      "anasayfa",
      "siparis",
      "sorgulama",
    ],
    path: "Crm",
    screen: "FindOrder",
    params: {},
    title: "Anasayfa -> CRM -> Sipariş Sorgulama",
  },
  {
    keywords: ["duyuru", "duyurular", "anasayfa"],
    path: "Notification",
    screen: "NotificationMain",
    params: {},
    title: "Anasayfa -> Duyurular",
  },
  {
    keywords: ["link", "lınk", "anasayfa", "yardimci linkler"],
    path: "Link",
    screen: "Link",
    params: {},
    title: "Anasayfa -> Linkler",
  },
  {
    keywords: ["sepet", "sepetlerim"],
    path: "Iso",
    screen: "BasketList",
    params: {},
    title: "Anasayfa -> Sepet Listesi",
  },
  {
    keywords: [
      "etiket",
      "yazici",
      "sezon",
      "konfigürasyon",
      "anasayfa",
      "zebra",
      "printer",
    ],
    path: "Printer",
    screen: "PrinterScreen",
    params: {},
    title: "Anasayfa -> Etiket Konfigürasyonu",
  },
  {
    keywords: ["oms", "paketleme", "mutabakat"],
    path: "Oms",
    screen: "OmsMain",
    params: {},
    title: "Anasayfa -> OMS",
  },
  {
    keywords: ["ides", "iade"],
    path: "Ides",
    screen: "FindFiche",
    params: {},
    title: "Anasayfa -> IDES",
  },
  {
    keywords: ["selfcheckout", "flo hızlı kasa", "hızlı", "mobil app", "mobil app ile ödeme", "odeme", "ödeme"],
    path: "SelfCheckout",
    screen: "QueryScreen",
    params: {},
    title: "Anasayfa -> Mobil App İle Ödeme",
  },
  {
    keywords: ["iptal ", "iade", "ret kargo"],
    path: "Ides",
    screen: "CancellationScreen",
    params: {},
    title: "Anasayfa -> İptal İşlemleri",
  },
];
