export const SayaVeMensei = {
  Saya: [
    {
      sayaID: '41',
      saya_TR: 'MESH',
      saya_EN: 'MESH',
      saya_MK: 'ТКАЕНИНА',
      saya_KSV: 'Rjetë',
      saya_UKR: 'MESH',
    },
    {
      sayaID: '42',
      saya_TR: 'MICROPOLYESTER',
      saya_EN: 'MICROPOLYESTER',
      saya_MK: 'МИКРОПОЛИЕСТЕР',
      saya_KSV: 'MIKROPOLIESTER',
      saya_UKR: 'МІКРОПОЛІЕСТЕР',
    },
    {
      sayaID: '43',
      saya_TR: 'WOOL/FELT',
      saya_EN: 'WOOL/FELT',
      saya_MK: 'Волна / Чувствувам',
      saya_KSV: 'Lesh/NDIHJE',
      saya_UKR: 'ВОВНА/ПОВСТЬ',
    },
    {
      sayaID: '44',
      saya_TR: 'ÖRME',
      saya_EN: 'ÖRME',
      saya_MK: 'ПЛЕТЕНА',
      saya_KSV: 'e Thurur',
      saya_UKR: 'ТРИКОТАЖ',
    },
    {
      sayaID: '45',
      saya_TR: 'ACTION LEATHER',
      saya_EN: 'ACTION LEATHER',
      saya_MK: 'АКЦИЈА КОATА',
      saya_KSV: 'LEKURE VEPRIMI',
      saya_UKR: 'СПІЛОК З ПОЛІУРЕТАНОВИМ ПОКРИТТЯМ',
    },
    {
      sayaID: '46',
      saya_TR: 'METAL',
      saya_EN: 'METAL',
      saya_MK: 'МЕТАЛ',
      saya_KSV: 'METAL',
      saya_UKR: 'МЕТАЛ',
    },
    {
      sayaID: '47',
      saya_TR: 'STEEL',
      saya_EN: 'STEEL',
      saya_MK: 'ЧЕЛИК',
      saya_KSV: 'ÇELIKU',
      saya_UKR: 'СТАЛЬ',
    },
    {
      sayaID: '48',
      saya_TR: 'PLASTIC',
      saya_EN: 'PLASTIC',
      saya_MK: 'ПЛАСТИЧНО',
      saya_KSV: 'PLASTIKE',
      saya_UKR: 'ПЛАСТИК',
    },
    {
      sayaID: '49',
      saya_TR: 'ARTIFICIAL',
      saya_EN: 'ARTIFICIAL',
      saya_MK: 'Уметнички',
      saya_KSV: 'ARTIFICIAL',
      saya_UKR: 'ШТУЧНИЙ',
    },
    {
      sayaID: '50',
      saya_TR: 'PU (KROKO)',
      saya_EN: 'PU (KROKO)',
      saya_MK: 'Ткаенина (КРОКО)',
      saya_KSV: 'UP (KROKO)',
      saya_UKR: 'ПУ (КРОКОДИЛ)',
    },
    {
      sayaID: '51',
      saya_TR: 'PU (ANACONDA)',
      saya_EN: 'PU (ANACONDA)',
      saya_MK: 'Ткаенина (АНАКОНДА)',
      saya_KSV: 'PU (ANACONDA)',
      saya_UKR: 'ПУ (АНАКОНДА)',
    },
    {
      sayaID: '52',
      saya_TR: 'PU (SNAKE)',
      saya_EN: 'PU (SNAKE)',
      saya_MK: 'Ткаенина (ЗМИЈА)',
      saya_KSV: 'PU (Gjarpri)',
      saya_UKR: 'ПУ (ЗМІЯ)',
    },
    {
      sayaID: '1',
      saya_TR: 'LEATHER',
      saya_EN: 'LEATHER',
      saya_MK: 'Кожа',
      saya_KSV: 'LËKUR',
      saya_UKR: 'ШКІРА',
    },
    {
      sayaID: '2',
      saya_TR: 'TANNING LEATHER',
      saya_EN: 'TANNING LEATHER',
      saya_MK: 'Затемнување кожа',
      saya_KSV: 'LËKUR E RRANNDSIS',
      saya_UKR: 'ДУБЛЕНА ШКІРА',
    },
    {
      sayaID: '3',
      saya_TR: 'LEATHER (NUBUCK)',
      saya_EN: 'LEATHER (NUBUCK)',
      saya_MK: 'КО LEА (НУБУК)',
      saya_KSV: 'Lëkurë (NUBUCK)',
      saya_UKR: 'ШКІРА (НУБУК)',
    },
    {
      sayaID: '4',
      saya_TR: 'LEATHER (RUGAN)',
      saya_EN: 'LEATHER (RUGAN)',
      saya_MK: 'Кожа (Руган)',
      saya_KSV: 'Lëkurë (RUGAN)',
      saya_UKR: 'ШКІРА (ЛАКОВАНА)',
    },
    {
      sayaID: '5',
      saya_TR: 'LEATHER (SUEDE)',
      saya_EN: 'LEATHER (SUEDE)',
      saya_MK: 'Кожа (суеда)',
      saya_KSV: 'LËKUR(SUEDE)',
      saya_UKR: 'ШКІРА (ЗАМШЕВА)',
    },
    {
      sayaID: '6',
      saya_TR: 'PU',
      saya_EN: 'PU',
      saya_MK: 'ТКАЕНИНА',
      saya_KSV: 'PU',
      saya_UKR: 'ПУ',
    },
    {
      sayaID: '7',
      saya_TR: 'TANNING PU',
      saya_EN: 'TANNING PU',
      saya_MK: 'ТАНИРАЕ СТП',
      saya_KSV: 'TANNING PU',
      saya_UKR: 'ДУБЛЕНА ШКІРА ПУ',
    },
    {
      sayaID: '8',
      saya_TR: 'PU (NUBUCK)',
      saya_EN: 'PU (NUBUCK)',
      saya_MK: 'СТП (НУБУК)',
      saya_KSV: 'PU (NUBUCK)',
      saya_UKR: 'ПУ (НУБУК)',
    },
    {
      sayaID: '9',
      saya_TR: 'PU (RUGAN)',
      saya_EN: 'PU (RUGAN)',
      saya_MK: 'СТП (РУГАН)',
      saya_KSV: 'PU (RUGAN)',
      saya_UKR: 'ПУ (ЛАКОВАНА)',
    },
    {
      sayaID: '10',
      saya_TR: 'PU (SUEDE)',
      saya_EN: 'PU (SUEDE)',
      saya_MK: 'СТП (СУЕДЕ)',
      saya_KSV: 'PU (SUEDE)',
      saya_UKR: 'ПУ (ЗАМШЕВА)',
    },
    {
      sayaID: '11',
      saya_TR: 'TEXTILE',
      saya_EN: 'TEXTILE',
      saya_MK: 'ТЕКСТИЛ',
      saya_KSV: 'TEKSTIL',
      saya_UKR: 'ТЕКСТИЛЬ',
    },
    {
      sayaID: '12',
      saya_TR: 'TEXTILE (LINEN)',
      saya_EN: 'TEXTILE (LINEN)',
      saya_MK: 'ТЕКСТИЛ (ЛЕНЕН)',
      saya_KSV: 'TEKSTILE (LIRI)',
      saya_UKR: 'ТЕКСТИЛЬ (ЛЬОН)',
    },
    {
      sayaID: '13',
      saya_TR: 'TEXTILE (SATIN)',
      saya_EN: 'TEXTILE (SATIN)',
      saya_MK: 'ТЕКСТИЛ (САТИН)',
      saya_KSV: 'TEKSTILE (SATEN)',
      saya_UKR: 'ТЕКСТИЛЬ (САТИН)',
    },
    {
      sayaID: '14',
      saya_TR: 'TEXTILE (NET)',
      saya_EN: 'TEXTILE (NET)',
      saya_MK: 'ТЕКСТИЛ (НЕТ)',
      saya_KSV: 'TEKSTILE (NET)',
      saya_UKR: 'ТЕКСТИЛЬ (СІТКА)',
    },
    {
      sayaID: '15',
      saya_TR: 'TEXTILE (NYL)',
      saya_EN: 'TEXTILE (NYL)',
      saya_MK: 'ТЕКСТИЛ (NYL)',
      saya_KSV: 'TEKSTILE (NYL)',
      saya_UKR: 'ТЕКСТИЛЬ (НЕЙЛОН)',
    },
    {
      sayaID: '16',
      saya_TR: 'LEATHER/PU',
      saya_EN: 'LEATHER/PU',
      saya_MK: 'Кожа / СТП',
      saya_KSV: 'Lëkurë/PU',
      saya_UKR: 'ШКІРА/ПУ',
    },
    {
      sayaID: '17',
      saya_TR: 'LEATHER/TEXTILE',
      saya_EN: 'LEATHER/TEXTILE',
      saya_MK: 'Кожа / ТЕКСТИЛ',
      saya_KSV: 'LEKURE/TEKSTILE',
      saya_UKR: 'ШКІРА/ТЕКСТИЛЬ',
    },
    {
      sayaID: '18',
      saya_TR: 'PU/TEXTILE',
      saya_EN: 'PU/TEXTILE',
      saya_MK: 'СТП / ТЕКСТИЛ',
      saya_KSV: 'PU/TEKSTILE',
      saya_UKR: 'ПУ/ТЕКСТИЛЬ',
    },
    {
      sayaID: '19',
      saya_TR: 'WOVEN COTTON',
      saya_EN: 'WOVEN COTTON',
      saya_MK: 'Ткаен памук',
      saya_KSV: 'Pambuk i endur',
      saya_UKR: 'ТКАНА БАВОВНА',
    },
    {
      sayaID: '20',
      saya_TR: 'WOVEN POLYESTER',
      saya_EN: 'WOVEN POLYESTER',
      saya_MK: 'ПЛАКЕН ПОЛИЕСТЕР',
      saya_KSV: 'Poliestër e endur',
      saya_UKR: 'ТКАНИЙ ПОЛІЕСТЕР',
    },
    {
      sayaID: '21',
      saya_TR: 'WOVEN NYLON',
      saya_EN: 'WOVEN NYLON',
      saya_MK: 'ПЛАТЕН NYИЛОН',
      saya_KSV: 'Najloni i endur',
      saya_UKR: 'ТКАНИЙ НЕЙЛОН',
    },
    {
      sayaID: '22',
      saya_TR: 'KNITTED COTTON',
      saya_EN: 'KNITTED COTTON',
      saya_MK: 'ПЛАТЕН ПАТЕК',
      saya_KSV: 'Pambuk i thurur',
      saya_UKR: "В'ЯЗАНА БАВОВНА",
    },
    {
      sayaID: '23',
      saya_TR: 'KNITTED POLYESTER',
      saya_EN: 'KNITTED POLYESTER',
      saya_MK: 'ПЛЕТЕН ПОЛИЕСТЕР',
      saya_KSV: 'POLIESTER I THIRRUR',
      saya_UKR: "В'ЯЗАНИЙ ПОЛІЕСТЕР",
    },
    {
      sayaID: '24',
      saya_TR: 'KNITWEAR  ACRYLIC',
      saya_EN: 'KNITWEAR  ACRYLIC',
      saya_MK: 'Трикотажа АКРИЛСКА',
      saya_KSV: 'TREGTARE AKRILIKE',
      saya_UKR: 'АКРИЛОВИЙ ТРИКОТАЖ',
    },
    {
      sayaID: '25',
      saya_TR: 'PVC',
      saya_EN: 'PVC',
      saya_MK: 'ПВЦ',
      saya_KSV: 'PVC',
      saya_UKR: 'ПВХ',
    },
    {
      sayaID: '26',
      saya_TR: 'SEMI PU',
      saya_EN: 'SEMI PU',
      saya_MK: 'ПОЛУ СТП',
      saya_KSV: 'SEMI PU',
      saya_UKR: 'СЕМІ ПУ',
    },
    {
      sayaID: '27',
      saya_TR: 'PU (NYL)',
      saya_EN: 'PU (NYL)',
      saya_MK: 'ТКАЕНИНА',
      saya_KSV: 'UP (NYL)',
      saya_UKR: 'ПУ (НЕЙЛОН)',
    },
    {
      sayaID: '28',
      saya_TR: 'LEATHER/SUEDE',
      saya_EN: 'LEATHER/SUEDE',
      saya_MK: 'СУЕДЕ',
      saya_KSV: 'LEKURE/SUEDE',
      saya_UKR: 'ШКІРА/ЗАМША',
    },
    {
      sayaID: '29',
      saya_TR: 'SUEDE/PU',
      saya_EN: 'SUEDE/PU',
      saya_MK: 'СУЕДЕ / СТП',
      saya_KSV: 'SUEDE/PU',
      saya_UKR: 'ЗАМША/ПУ',
    },
    {
      sayaID: '30',
      saya_TR: 'NUBUCK/SUEDE',
      saya_EN: 'NUBUCK/SUEDE',
      saya_MK: 'НУБУК / СУЕДЕ',
      saya_KSV: 'NUBUCK/SUEDE',
      saya_UKR: 'НУБУК/ЗАМША',
    },
    {
      sayaID: '31',
      saya_TR: 'SUEDE/TEXTILE',
      saya_EN: 'SUEDE/TEXTILE',
      saya_MK: 'СУЕД / ТЕКСТИЛ',
      saya_KSV: 'SUEDE/TEKSTILE',
      saya_UKR: 'ЗАМША/ТЕКСТИЛЬ',
    },
    {
      sayaID: '32',
      saya_TR: 'SILICON',
      saya_EN: 'SILICON',
      saya_MK: 'Силикон',
      saya_KSV: 'SILIKON',
      saya_UKR: 'CИЛІКОН',
    },
    {
      sayaID: '33',
      saya_TR: 'WICKER',
      saya_EN: 'WICKER',
      saya_MK: 'ПОДОБРИ',
      saya_KSV: 'THURJE',
      saya_UKR: 'ПЛЕТЕНА ТКАНИНА',
    },
    {
      sayaID: '34',
      saya_TR: 'COTTON',
      saya_EN: 'COTTON',
      saya_MK: 'Памук',
      saya_KSV: 'Pambuku',
      saya_UKR: 'БАВОВНА',
    },
    {
      sayaID: '35',
      saya_TR: 'MICROFIBER',
      saya_EN: 'MICROFIBER',
      saya_MK: 'Микрофибер',
      saya_KSV: 'MIKROFIBER',
      saya_UKR: 'МІКРОВОЛОКНО',
    },
    {
      sayaID: '36',
      saya_TR: 'POLYCOTTON',
      saya_EN: 'POLYCOTTON',
      saya_MK: 'ПОЛИКОТОН',
      saya_KSV: 'POLIKOTON',
      saya_UKR: 'ПОЛІБАВОВНА',
    },
    {
      sayaID: '37',
      saya_TR: 'SUEDE/LINEN',
      saya_EN: 'SUEDE/LINEN',
      saya_MK: 'СУЕДЕ / ЛЕН',
      saya_KSV: 'SUEDE/LINEN',
      saya_UKR: 'ЗАМША/ЛЬОН',
    },
    {
      sayaID: '38',
      saya_TR: 'LINEN/PU',
      saya_EN: 'LINEN/PU',
      saya_MK: 'ЛЕН/ ТКАЕНИНА',
      saya_KSV: 'LINEN/PU',
      saya_UKR: 'ЛЬОН/ПУ',
    },
    {
      sayaID: '39',
      saya_TR: 'POLAR',
      saya_EN: 'POLAR',
      saya_MK: 'ПОЛАРНО',
      saya_KSV: 'POLAR',
      saya_UKR: 'ФЛІС',
    },
    {
      sayaID: '40',
      saya_TR: 'CANVAS',
      saya_EN: 'CANVAS',
      saya_MK: 'ПЛАТНО',
      saya_KSV: 'Kanavacë',
      saya_UKR: 'КАНВАС',
    },
    {
      sayaID: '53',
      saya_TR: 'PU (LIZARD)',
      saya_EN: 'PU (LIZARD)',
      saya_MK: 'Ткаенина ',
      saya_KSV: 'PU (LIZARD)',
      saya_UKR: 'ПУ (ЯЩІРКА)',
    },
    {
      sayaID: '54',
      saya_TR: 'PU (ZEBRA)',
      saya_EN: 'PU (ZEBRA)',
      saya_MK: 'Ткаенина (ЗЕБРА)',
      saya_KSV: 'PU (ZEBRA)',
      saya_UKR: 'ПУ (ЗЕБРА)',
    },
    {
      sayaID: '55',
      saya_TR: 'PU (LEOPARD)',
      saya_EN: 'PU (LEOPARD)',
      saya_MK: 'Ткаенина (ЛЕОПАРД)',
      saya_KSV: 'PU (LEOPARD)',
      saya_UKR: 'ПУ (ЛЕОПАРД)',
    },
    {
      sayaID: '56',
      saya_TR: 'PU (FOAL)',
      saya_EN: 'PU (FOAL)',
      saya_MK: 'Ткаенина ',
      saya_KSV: 'PU (FOAL)',
      saya_UKR: 'ПУ (ЖЕРЕБЕЦЬ)',
    },
    {
      sayaID: '57',
      saya_TR: 'LEATHER (KROKO)',
      saya_EN: 'LEATHER (KROKO)',
      saya_MK: 'Кожа (КРОКО)',
      saya_KSV: 'Lëkurë (KROKO)',
      saya_UKR: 'ШКІРА (КРОКОДИЛ)',
    },
    {
      sayaID: '58',
      saya_TR: 'LEATHER (ANACONDA)',
      saya_EN: 'LEATHER (ANACONDA)',
      saya_MK: 'Кожа (АНАКОНДА)',
      saya_KSV: 'Lëkurë (ANACONDA)',
      saya_UKR: 'ШКІРА (АНАКОНДА)',
    },
    {
      sayaID: '59',
      saya_TR: 'LEADER (SNAKE)',
      saya_EN: 'LEADER (SNAKE)',
      saya_MK: 'ЛИДЕР (ЗМИЈА)',
      saya_KSV: 'Lëkurë ( Gjarpri)',
      saya_UKR: 'ШКІРА (ЗМІЯ)',
    },
    {
      sayaID: '60',
      saya_TR: 'LEATHER (LIZARD)',
      saya_EN: 'LEATHER (LIZARD)',
      saya_MK: 'Кожа (гуштер)',
      saya_KSV: 'LEKUR (LIZARD)',
      saya_UKR: 'ШКІРА (ЯЩІРКА)',
    },
    {
      sayaID: '61',
      saya_TR: 'LEATHER (ZEBRA)',
      saya_EN: 'LEATHER (ZEBRA)',
      saya_MK: 'Кожа (ЗЕБРА)',
      saya_KSV: 'LEKURE (ZEBRA)',
      saya_UKR: 'ШКІРА (ЗЕБРА)',
    },
    {
      sayaID: '62',
      saya_TR: 'LEATHER (LEOPARD)',
      saya_EN: 'LEATHER (LEOPARD)',
      saya_MK: 'Кожа (Леопард)',
      saya_KSV: 'Lëkurë (LEOPARD)',
      saya_UKR: 'ШКІРА (ЛЕОПАРД)',
    },
    {
      sayaID: '63',
      saya_TR: 'LEATHER (FOAL)',
      saya_EN: 'LEATHER (FOAL)',
      saya_MK: 'КО LEА (ФОЛ)',
      saya_KSV: 'LEKUR (FOAL)',
      saya_UKR: 'ШКІРА (ЖЕРЕБЕЦЬ)',
    },
    {
      sayaID: '65',
      saya_TR: 'PHYLON',
      saya_EN: 'PHYLON',
      saya_MK: 'ФИЛОН',
      saya_KSV: 'FYLON',
      saya_UKR: 'ФІЛОН',
    },
    {
      sayaID: '99',
      saya_TR: 'ACCS.',
      saya_EN: 'ACCS.',
      saya_MK: 'ACCS.',
      saya_KSV: 'ACCS.',
      saya_UKR: 'ACCS.',
    },
    {
      sayaID: '100',
      saya_TR: 'ORGU',
      saya_EN: 'ORGU',
      saya_MK: 'ПЛЕТЕНА',
      saya_KSV: 'Thurje ',
      saya_UKR: "В'ЯЗАННЯ",
    },
    {
      sayaID: '101',
      saya_TR: 'PU/MESH',
      saya_EN: 'PU/MESH',
      saya_MK: 'ТКАЕНИНА',
      saya_KSV: 'UP/MESH',
      saya_UKR: 'ПУ/MESH',
    },
    {
      sayaID: '102',
      saya_TR: 'POLIPROPILEN',
      saya_EN: 'POLIPROPILEN',
      saya_MK: 'ПОЛИПРОПИЛЕН',
      saya_KSV: 'POLIPROPILEN',
      saya_UKR: 'ПОЛІПРОПІЛЕН',
    },
    {
      sayaID: '103',
      saya_TR: 'PU/MICROFIBER',
      saya_EN: 'PU/MICROFIBER',
      saya_MK: 'ТКАЕНИНА / МИКРОФИБЕР',
      saya_KSV: 'UP/MIKROFIBER',
      saya_UKR: 'ПУ/МІКРОВОЛОКНА',
    },
    {
      sayaID: '104',
      saya_TR: 'DELIKLI',
      saya_EN: 'DELIKLI',
      saya_MK: 'ТЕКСТИЛ',
      saya_KSV: 'I Shpuar ',
      saya_UKR: 'ПЕРФОРОВАНА',
    },
  ],
  Mensei: [
    {
      menseiID: 'PL',
      mensei_TR: 'Polonya',
      mensei_EN: 'Poland',
      mensei_MK: 'Полска',
      mensei_UKR: 'Польща',
      mensei_KSV: 'Polonia',
    },
    {
      menseiID: 'PM',
      mensei_TR: 'St.Pier,Miquel.',
      mensei_EN: 'St. Pierre, Miquel.',
      mensei_MK: 'Сент Пјер, Микел.',
      mensei_UKR: "Сен-П'єр, Мікель.",
      mensei_KSV: 'Shën Pierre, Miquel.',
    },
    {
      menseiID: 'PN',
      mensei_TR: 'Pitcairn Adl.',
      mensei_EN: 'Pitcairn Adl.',
      mensei_MK: 'Питкерн Адл.',
      mensei_UKR: 'Піткерн Адл.',
      mensei_KSV: 'Pitcairn Adl.',
    },
    {
      menseiID: 'PR',
      mensei_TR: 'Porto Riko',
      mensei_EN: 'Porto Rico',
      mensei_MK: 'Порто Рико',
      mensei_UKR: 'Порто-Ріко',
      mensei_KSV: 'Porto Riko',
    },
    {
      menseiID: 'PS',
      mensei_TR: 'Filistin',
      mensei_EN: 'Palestine',
      mensei_MK: 'Палестина',
      mensei_UKR: 'Палестина',
      mensei_KSV: 'Palestinë',
    },
    {
      menseiID: 'PT',
      mensei_TR: 'Portekiz',
      mensei_EN: 'Portugal',
      mensei_MK: 'Португалија',
      mensei_UKR: 'Португалія',
      mensei_KSV: 'Portugalia',
    },
    {
      menseiID: 'PW',
      mensei_TR: 'Palau',
      mensei_EN: 'Palau',
      mensei_MK: 'Палау',
      mensei_UKR: 'Палау',
      mensei_KSV: 'Palau',
    },
    {
      menseiID: 'PY',
      mensei_TR: 'Paraguay',
      mensei_EN: 'Paraguay',
      mensei_MK: 'Парагвај',
      mensei_UKR: 'Парагвай',
      mensei_KSV: 'Paraguai',
    },
    {
      menseiID: 'QA',
      mensei_TR: 'Katar',
      mensei_EN: 'Train',
      mensei_MK: 'Воз',
      mensei_UKR: 'Поїзд',
      mensei_KSV: 'Treni',
    },
    {
      menseiID: 'RE',
      mensei_TR: 'Reunion',
      mensei_EN: 'Reunion',
      mensei_MK: 'Средба',
      mensei_UKR: "Возз'єднання",
      mensei_KSV: 'Ribashkim',
    },
    {
      menseiID: 'RO',
      mensei_TR: 'Romanya',
      mensei_EN: 'Romania',
      mensei_MK: 'Романија',
      mensei_UKR: 'Румунія',
      mensei_KSV: 'Rumania',
    },
    {
      menseiID: 'RU',
      mensei_TR: 'Rusya Fed.',
      mensei_EN: 'Russian Fed.',
      mensei_MK: 'Руски Банката на федерални резерви.',
      mensei_UKR: 'Російський ФРС.',
      mensei_KSV: 'Fed Ruse.',
    },
    {
      menseiID: 'RW',
      mensei_TR: 'Ruanda',
      mensei_EN: 'Rwanda',
      mensei_MK: 'Руанда',
      mensei_UKR: 'Руанда',
      mensei_KSV: 'Ruanda',
    },
    {
      menseiID: 'SA',
      mensei_TR: 'Suudi Arabistan',
      mensei_EN: 'Saudi Arabia',
      mensei_MK: 'Саудиска Арабија',
      mensei_UKR: 'Саудівська Аравія',
      mensei_KSV: 'Arabia Saudite',
    },
    {
      menseiID: 'SB',
      mensei_TR: 'Solomon Adaları',
      mensei_EN: 'Solomon Islands',
      mensei_MK: 'Соломонски острови',
      mensei_UKR: 'Соломонові острови',
      mensei_KSV: 'Ishujt Solomon',
    },
    {
      menseiID: 'SC',
      mensei_TR: 'Seyşeller',
      mensei_EN: 'Seychelles',
      mensei_MK: 'Сејшели',
      mensei_UKR: 'Сейшельські острови',
      mensei_KSV: 'Sishel',
    },
    {
      menseiID: 'SD',
      mensei_TR: 'Sudan',
      mensei_EN: 'Sudan',
      mensei_MK: 'Судан',
      mensei_UKR: 'Судан',
      mensei_KSV: 'Sudani',
    },
    {
      menseiID: 'SE',
      mensei_TR: 'İsveç',
      mensei_EN: 'Sweden',
      mensei_MK: 'Шведска',
      mensei_UKR: 'Швеція',
      mensei_KSV: 'Suedia',
    },
    {
      menseiID: 'SG',
      mensei_TR: 'Singapur',
      mensei_EN: 'Singapore',
      mensei_MK: 'Сингапур',
      mensei_UKR: 'Сінгапур',
      mensei_KSV: 'Singapori',
    },
    {
      menseiID: 'SH',
      mensei_TR: 'St. Helena',
      mensei_EN: 'St. Helena',
      mensei_MK: 'Св. Хелена',
      mensei_UKR: 'Святої Єлени',
      mensei_KSV: 'Shën Helena',
    },
    {
      menseiID: 'SI',
      mensei_TR: 'Slovenya',
      mensei_EN: 'Slovenia',
      mensei_MK: 'Словенија',
      mensei_UKR: 'Словенія',
      mensei_KSV: 'Sllovenia',
    },
    {
      menseiID: 'SJ',
      mensei_TR: 'Svalbard',
      mensei_EN: 'Svalbard',
      mensei_MK: 'Свалбард',
      mensei_UKR: 'Шпіцберген',
      mensei_KSV: 'Svalbard',
    },
    {
      menseiID: 'SK',
      mensei_TR: 'Slovakya',
      mensei_EN: 'Slovakia',
      mensei_MK: 'Словачка',
      mensei_UKR: 'Словаччина',
      mensei_KSV: 'Sllovakia',
    },
    {
      menseiID: 'SL',
      mensei_TR: 'Sierra Leone',
      mensei_EN: 'Sierra leone',
      mensei_MK: 'Сиера Леоне',
      mensei_UKR: 'Сьєрра-Леоне',
      mensei_KSV: 'Sierra Leone',
    },
    {
      menseiID: 'SM',
      mensei_TR: 'San Marino',
      mensei_EN: 'San Marino',
      mensei_MK: 'Сан Марино',
      mensei_UKR: 'Сан-Марино',
      mensei_KSV: 'San Marino',
    },
    {
      menseiID: 'SN',
      mensei_TR: 'Senegal',
      mensei_EN: 'Senegal',
      mensei_MK: 'Сенегал',
      mensei_UKR: 'Сенегал',
      mensei_KSV: 'Senegali',
    },
    {
      menseiID: 'SO',
      mensei_TR: 'Somali',
      mensei_EN: 'Somalia',
      mensei_MK: 'Сомалија',
      mensei_UKR: 'Сомалі',
      mensei_KSV: 'Somali',
    },
    {
      menseiID: 'SR',
      mensei_TR: 'Surinam',
      mensei_EN: 'Suriname',
      mensei_MK: 'Суринам',
      mensei_UKR: 'Суринам',
      mensei_KSV: 'Suriname',
    },
    {
      menseiID: 'ST',
      mensei_TR: 'S.Tome,Principe',
      mensei_EN: 'S. Tome, Principe',
      mensei_MK: 'С. Томе, Принципе',
      mensei_UKR: 'С. Томе, Принсіпі',
      mensei_KSV: 'S. Tome, Principe',
    },
    {
      menseiID: 'SV',
      mensei_TR: 'El Salvador',
      mensei_EN: 'El Salvador',
      mensei_MK: 'Ел Салвадор',
      mensei_UKR: 'Сальвадор',
      mensei_KSV: 'El Salvador',
    },
    {
      menseiID: 'SY',
      mensei_TR: 'Suriye',
      mensei_EN: 'Syria',
      mensei_MK: 'Сирија',
      mensei_UKR: 'Сирія',
      mensei_KSV: 'Siria',
    },
    {
      menseiID: 'SZ',
      mensei_TR: 'Svaziland',
      mensei_EN: 'Swaziland',
      mensei_MK: 'Свазиленд',
      mensei_UKR: 'Свазіленд',
      mensei_KSV: 'Svaziland',
    },
    {
      menseiID: 'TC',
      mensei_TR: 'Turks&Caicos Ad',
      mensei_EN: 'Turks & Caicos Ad',
      mensei_MK: 'Турк & Каикос Ад',
      mensei_UKR: 'Оголошення Теркс і Кайкос',
      mensei_KSV: 'Turks & Caicos Ad',
    },
    {
      menseiID: 'TD',
      mensei_TR: 'Çad',
      mensei_EN: 'Chad',
      mensei_MK: 'Чад',
      mensei_UKR: 'Чад',
      mensei_KSV: 'Çad',
    },
    {
      menseiID: 'TF',
      mensei_TR: 'Frans.Gün.Topr.',
      mensei_EN: 'Frans.Gün.Topr.',
      mensei_MK: 'Франс.Гин.Топр.',
      mensei_UKR: 'Франс. Гюн. Топр.',
      mensei_KSV: 'Frans.Gün.Topr.',
    },
    {
      menseiID: 'TG',
      mensei_TR: 'Togo',
      mensei_EN: 'Togo',
      mensei_MK: 'Да оди',
      mensei_UKR: 'Йти',
      mensei_KSV: 'Togo',
    },
    {
      menseiID: 'TH',
      mensei_TR: 'Tayland',
      mensei_EN: 'Thailand',
      mensei_MK: 'Тајланд',
      mensei_UKR: 'Таїланд',
      mensei_KSV: 'Tajlandë',
    },
    {
      menseiID: 'TJ',
      mensei_TR: 'Tacikistan',
      mensei_EN: 'Tajikistan',
      mensei_MK: 'Таџикистан',
      mensei_UKR: 'Таджикистан',
      mensei_KSV: 'Taxhikistani',
    },
    {
      menseiID: 'TK',
      mensei_TR: 'Tokelau Adaları',
      mensei_EN: 'Tokelau Islands',
      mensei_MK: 'Острови Токелау',
      mensei_UKR: 'Острови Токелау',
      mensei_KSV: 'Ishujt Tokelau',
    },
    {
      menseiID: 'TL',
      mensei_TR: 'Osttimor',
      mensei_EN: 'Osttimor',
      mensei_MK: 'Остимор',
      mensei_UKR: 'Осттімор',
      mensei_KSV: 'Osttimor',
    },
    {
      menseiID: 'TM',
      mensei_TR: 'Türkmenistan',
      mensei_EN: 'Turkmenistan',
      mensei_MK: 'Туркменистан',
      mensei_UKR: 'Туркменістан',
      mensei_KSV: 'Turkmenistani',
    },
    {
      menseiID: 'TN',
      mensei_TR: 'Tunus',
      mensei_EN: 'Tunisia',
      mensei_MK: 'Тунис',
      mensei_UKR: 'Туніс',
      mensei_KSV: 'Tunizi',
    },
    {
      menseiID: 'TO',
      mensei_TR: 'Tonga',
      mensei_EN: 'Tonga',
      mensei_MK: 'Тонга',
      mensei_UKR: 'Тонга',
      mensei_KSV: 'Tonga',
    },
    {
      menseiID: 'TP',
      mensei_TR: 'Doğu Timor',
      mensei_EN: 'East Timor',
      mensei_MK: 'Источен Тимор',
      mensei_UKR: 'Східний Тимор',
      mensei_KSV: 'Timori Lindor',
    },
    {
      menseiID: 'TR',
      mensei_TR: 'Türkiye',
      mensei_EN: 'Turkey',
      mensei_MK: 'Турција',
      mensei_UKR: 'Туреччина',
      mensei_KSV: 'Turqia',
    },
    {
      menseiID: 'TT',
      mensei_TR: 'Trinidad,Tobago',
      mensei_EN: 'Trinidad, Tobago',
      mensei_MK: 'Тринидад, Тобаго',
      mensei_UKR: 'Тринідад, Тобаго',
      mensei_KSV: 'Trinidad, Tobago',
    },
    {
      menseiID: 'TV',
      mensei_TR: 'Tuvalu',
      mensei_EN: 'Tuvalu',
      mensei_MK: 'Тувалу',
      mensei_UKR: 'Тувалу',
      mensei_KSV: 'Tuvalu',
    },
    {
      menseiID: 'TW',
      mensei_TR: 'Tayvan',
      mensei_EN: 'Taiwan',
      mensei_MK: 'Тајван',
      mensei_UKR: 'Тайвань',
      mensei_KSV: 'Tajvani',
    },
    {
      menseiID: 'TZ',
      mensei_TR: 'Tanzanya',
      mensei_EN: 'Tanzania',
      mensei_MK: 'Танзанија',
      mensei_UKR: 'Танзанія',
      mensei_KSV: 'Tanzani',
    },
    {
      menseiID: 'UA',
      mensei_TR: 'Ukrayna',
      mensei_EN: 'Ukraine',
      mensei_MK: 'Украина',
      mensei_UKR: 'Україна',
      mensei_KSV: 'Ukraina',
    },
    {
      menseiID: 'UG',
      mensei_TR: 'Uganda',
      mensei_EN: 'Uganda',
      mensei_MK: 'Уганда',
      mensei_UKR: 'Уганда',
      mensei_KSV: 'Uganda',
    },
    {
      menseiID: 'UM',
      mensei_TR: 'Minor Outl.Adl.',
      mensei_EN: 'Minor Outl. Adl.',
      mensei_MK: 'Мало засилување.',
      mensei_UKR: 'Незначні результати Adl.',
      mensei_KSV: 'Përmbledhje e vogël. Adl.',
    },
    {
      menseiID: 'UN',
      mensei_TR: 'Birleşmiş mllt.',
      mensei_EN: 'United mllt.',
      mensei_MK: 'Јунајтед млт.',
      mensei_UKR: 'United mllt.',
      mensei_KSV: 'United mllt.',
    },
    {
      menseiID: 'US',
      mensei_TR: 'ABD',
      mensei_EN: 'USA',
      mensei_MK: 'САД',
      mensei_UKR: 'США',
      mensei_KSV: 'SHBA',
    },
    {
      menseiID: 'UY',
      mensei_TR: 'Uruguay',
      mensei_EN: 'Uruguay',
      mensei_MK: 'Уругвај',
      mensei_UKR: 'Уругвай',
      mensei_KSV: 'Uruguaj',
    },
    {
      menseiID: 'UZ',
      mensei_TR: 'Özbekistan',
      mensei_EN: 'Uzbekistan',
      mensei_MK: 'Узбекистан',
      mensei_UKR: 'Узбекистан',
      mensei_KSV: 'Uzbekistani',
    },
    {
      menseiID: 'VA',
      mensei_TR: 'Vatikan',
      mensei_EN: 'Vatican',
      mensei_MK: 'Ватикан',
      mensei_UKR: 'Ватикан',
      mensei_KSV: 'Vatikani',
    },
    {
      menseiID: 'VC',
      mensei_TR: 'St. Vincent',
      mensei_EN: 'St. Vincent',
      mensei_MK: 'Св. Винсент',
      mensei_UKR: 'Сент-Вінсент',
      mensei_KSV: 'Shën Vincenti',
    },
    {
      menseiID: 'AD',
      mensei_TR: 'Andorra',
      mensei_EN: 'Andorra',
      mensei_MK: 'Андора',
      mensei_UKR: 'Андорра',
      mensei_KSV: 'Andorra',
    },
    {
      menseiID: 'AE',
      mensei_TR: 'BAE',
      mensei_EN: 'UAE',
      mensei_MK: 'ОАЕ',
      mensei_UKR: 'ОАЕ',
      mensei_KSV: 'Emiratet e Bashkuara Arabe',
    },
    {
      menseiID: 'AF',
      mensei_TR: 'Afganistan',
      mensei_EN: 'Afghanistan',
      mensei_MK: 'Авганистан',
      mensei_UKR: 'Афганістан',
      mensei_KSV: 'Afganistan',
    },
    {
      menseiID: 'AG',
      mensei_TR: 'Antigua/Barbuda',
      mensei_EN: 'Antigua / Barbuda',
      mensei_MK: 'Антигва / Барбуда',
      mensei_UKR: 'Антигуа / Барбуда',
      mensei_KSV: 'Antigua / Barbuda',
    },
    {
      menseiID: 'AI',
      mensei_TR: 'Anguilla',
      mensei_EN: 'Anguilla',
      mensei_MK: 'Ангилја',
      mensei_UKR: 'Ангілья',
      mensei_KSV: 'Anguilla',
    },
    {
      menseiID: 'AL',
      mensei_TR: 'Arnavutluk',
      mensei_EN: 'Albania',
      mensei_MK: 'Албанија',
      mensei_UKR: 'Албанія',
      mensei_KSV: 'Shqipëria',
    },
    {
      menseiID: 'AM',
      mensei_TR: 'Ermenistan',
      mensei_EN: 'Armenia',
      mensei_MK: 'Ерменија',
      mensei_UKR: 'Вірменія',
      mensei_KSV: 'Armenia',
    },
    {
      menseiID: 'AN',
      mensei_TR: 'Hol.Antilleri',
      mensei_EN: 'Hall Antilles',
      mensei_MK: 'Сала Антили',
      mensei_UKR: 'Антильські острови',
      mensei_KSV: 'Sallat e Antileve',
    },
    {
      menseiID: 'AO',
      mensei_TR: 'Angola',
      mensei_EN: 'Angola',
      mensei_MK: 'Ангола',
      mensei_UKR: 'Ангола',
      mensei_KSV: 'Angola',
    },
    {
      menseiID: 'AQ',
      mensei_TR: 'Antarktika',
      mensei_EN: 'Antarctica',
      mensei_MK: 'Антарктикот',
      mensei_UKR: 'Антарктида',
      mensei_KSV: 'Antarktida',
    },
    {
      menseiID: 'AR',
      mensei_TR: 'Arjantin',
      mensei_EN: 'Argentina',
      mensei_MK: 'Аргентина',
      mensei_UKR: 'Аргентина',
      mensei_KSV: 'Argjentina',
    },
    {
      menseiID: 'AS',
      mensei_TR: 'Amerik.Samoası',
      mensei_EN: 'America sama',
      mensei_MK: 'Америка сама',
      mensei_UKR: 'Америка сама',
      mensei_KSV: 'Amerika sama',
    },
    {
      menseiID: 'AT',
      mensei_TR: 'Avusturya',
      mensei_EN: 'Austria',
      mensei_MK: 'Австрија',
      mensei_UKR: 'Австрія',
      mensei_KSV: 'Austria',
    },
    {
      menseiID: 'AU',
      mensei_TR: 'Avustralya',
      mensei_EN: 'Australia',
      mensei_MK: 'Австралија',
      mensei_UKR: 'Австралія',
      mensei_KSV: 'Australi',
    },
    {
      menseiID: 'AW',
      mensei_TR: 'Aruba',
      mensei_EN: 'Aruba',
      mensei_MK: 'Аруба',
      mensei_UKR: 'Аруба',
      mensei_KSV: 'Aruba',
    },
    {
      menseiID: 'AZ',
      mensei_TR: 'Azerbaycan',
      mensei_EN: 'Azerbaijan',
      mensei_MK: 'Азербејџан',
      mensei_UKR: 'Азербайджан',
      mensei_KSV: 'Azerbajxhani',
    },
    {
      menseiID: 'BA',
      mensei_TR: 'Bosna Hersek',
      mensei_EN: 'Bosnia and Herzegovina',
      mensei_MK: 'Босна и Херцеговина',
      mensei_UKR: 'Боснія і Герцеговина',
      mensei_KSV: 'Bosnja dhe Hercegovinë',
    },
    {
      menseiID: 'BB',
      mensei_TR: 'Barbados',
      mensei_EN: 'Barbados',
      mensei_MK: 'Барбадос',
      mensei_UKR: 'Барбадос',
      mensei_KSV: 'Barbados',
    },
    {
      menseiID: 'BD',
      mensei_TR: 'Bangladeş',
      mensei_EN: 'Bangladesh',
      mensei_MK: 'Бангладеш',
      mensei_UKR: 'Бангладеш',
      mensei_KSV: 'Bangladeshi',
    },
    {
      menseiID: 'BE',
      mensei_TR: 'Belçika',
      mensei_EN: 'Belgium',
      mensei_MK: 'Белгија',
      mensei_UKR: 'Бельгія',
      mensei_KSV: 'Belgjika',
    },
    {
      menseiID: 'BF',
      mensei_TR: 'Burkina Faso',
      mensei_EN: 'Burkina Faso',
      mensei_MK: 'Буркина Фасо',
      mensei_UKR: 'Буркіна-Фасо',
      mensei_KSV: 'Burkina Faso',
    },
    {
      menseiID: 'BG',
      mensei_TR: 'Bulgaristan',
      mensei_EN: 'Bulgaria',
      mensei_MK: 'Бугарија',
      mensei_UKR: 'Болгарія',
      mensei_KSV: 'Bullgaria',
    },
    {
      menseiID: 'BH',
      mensei_TR: 'Bahreyn',
      mensei_EN: 'Bahrain',
      mensei_MK: 'Бахреин',
      mensei_UKR: 'Бахрейн',
      mensei_KSV: 'Bahrein',
    },
    {
      menseiID: 'BI',
      mensei_TR: 'Burundi',
      mensei_EN: 'Burundi',
      mensei_MK: 'Бурунди',
      mensei_UKR: 'Бурунді',
      mensei_KSV: 'Burundi',
    },
    {
      menseiID: 'BJ',
      mensei_TR: 'Benin',
      mensei_EN: 'Benin',
      mensei_MK: 'Бенин',
      mensei_UKR: 'Бенін',
      mensei_KSV: 'Benin',
    },
    {
      menseiID: 'BL',
      mensei_TR: 'Mavi',
      mensei_EN: 'blue',
      mensei_MK: 'сина',
      mensei_UKR: 'блакитний',
      mensei_KSV: 'blu',
    },
    {
      menseiID: 'BM',
      mensei_TR: 'Bermuda',
      mensei_EN: 'Bermuda',
      mensei_MK: 'Бермуди',
      mensei_UKR: 'Бермудські острови',
      mensei_KSV: 'Bermuda',
    },
    {
      menseiID: 'BN',
      mensei_TR: 'Brunei Dar-es-S',
      mensei_EN: 'Brunei Dar-es-S',
      mensei_MK: 'Брунеи Дар-ес-С',
      mensei_UKR: 'Бруней Дар-ес-С',
      mensei_KSV: 'Brunei Dar-es-S',
    },
    {
      menseiID: 'BO',
      mensei_TR: 'Bolivya',
      mensei_EN: 'Bolivia',
      mensei_MK: 'Боливија',
      mensei_UKR: 'Болівія',
      mensei_KSV: 'Bolivia',
    },
    {
      menseiID: 'BR',
      mensei_TR: 'Brezilya',
      mensei_EN: 'Brazil',
      mensei_MK: 'Бразил',
      mensei_UKR: 'Бразилія',
      mensei_KSV: 'Brazil',
    },
    {
      menseiID: 'BS',
      mensei_TR: 'Bahamalar',
      mensei_EN: 'Bahamas',
      mensei_MK: 'Бахами',
      mensei_UKR: 'Багамські острови',
      mensei_KSV: 'Bahamas',
    },
    {
      menseiID: 'BT',
      mensei_TR: 'Bhutan',
      mensei_EN: 'Bhutan',
      mensei_MK: 'Бутан',
      mensei_UKR: 'Бутан',
      mensei_KSV: 'Butan',
    },
    {
      menseiID: 'BV',
      mensei_TR: 'Buvet Adaları',
      mensei_EN: 'Buvet Islands',
      mensei_MK: 'Буветски острови',
      mensei_UKR: 'Острови Буве',
      mensei_KSV: 'Ishujt Buvet',
    },
    {
      menseiID: 'BW',
      mensei_TR: 'Botsvana',
      mensei_EN: 'Botswana',
      mensei_MK: 'Боцвана',
      mensei_UKR: 'Ботсвана',
      mensei_KSV: 'Botsvana',
    },
    {
      menseiID: 'BY',
      mensei_TR: 'Beyaz Rusya',
      mensei_EN: 'Belarus',
      mensei_MK: 'Белорусија',
      mensei_UKR: 'Білорусь',
      mensei_KSV: 'Bjellorusia',
    },
    {
      menseiID: 'BZ',
      mensei_TR: 'Belize',
      mensei_EN: 'Belize',
      mensei_MK: 'Белизе',
      mensei_UKR: 'Беліз',
      mensei_KSV: 'Belize',
    },
    {
      menseiID: 'CA',
      mensei_TR: 'Kanada',
      mensei_EN: 'Canada',
      mensei_MK: 'Канада',
      mensei_UKR: 'Канада',
      mensei_KSV: 'Kanadaja',
    },
    {
      menseiID: 'CC',
      mensei_TR: 'Cocos Adaları',
      mensei_EN: 'Cocos Islands',
      mensei_MK: 'Острови Кокос',
      mensei_UKR: 'Кокосові острови',
      mensei_KSV: 'Ishujt Cocos',
    },
    {
      menseiID: 'CD',
      mensei_TR: 'Kongo',
      mensei_EN: 'Congo',
      mensei_MK: 'Конго',
      mensei_UKR: 'Конго',
      mensei_KSV: 'Kongo',
    },
    {
      menseiID: 'CF',
      mensei_TR: 'Orta Afrika Cum',
      mensei_EN: 'Central African Rep',
      mensei_MK: 'Централноафрикански претставник',
      mensei_UKR: 'Центральноафриканська Республіка',
      mensei_KSV: 'Përfaqësuesja e Afrikës Qendrore',
    },
    {
      menseiID: 'CG',
      mensei_TR: 'Kongo',
      mensei_EN: 'Congo',
      mensei_MK: 'Конго',
      mensei_UKR: 'Конго',
      mensei_KSV: 'Kongo',
    },
    {
      menseiID: 'CH',
      mensei_TR: 'İsviçre',
      mensei_EN: 'Switzerland',
      mensei_MK: 'Швајцарија',
      mensei_UKR: 'Швейцарія',
      mensei_KSV: 'Zvicra',
    },
    {
      menseiID: 'CI',
      mensei_TR: 'Fildişi Kıyısı',
      mensei_EN: 'Ivory Coast',
      mensei_MK: 'Брегот на Слоновата Коска',
      mensei_UKR: 'Берег Слонової Кістки',
      mensei_KSV: 'Bregu i Fildishtë',
    },
    {
      menseiID: 'CK',
      mensei_TR: 'Cook Adaları',
      mensei_EN: 'Cook Islands',
      mensei_MK: 'Кукови острови',
      mensei_UKR: 'Острови Кука',
      mensei_KSV: 'Ishujt Kuk',
    },
    {
      menseiID: 'CL',
      mensei_TR: 'Şili',
      mensei_EN: 'Chile',
      mensei_MK: 'Чиле',
      mensei_UKR: 'Чилі',
      mensei_KSV: 'Kili',
    },
    {
      menseiID: 'CM',
      mensei_TR: 'Kamerun',
      mensei_EN: 'Cameroon',
      mensei_MK: 'Камерун',
      mensei_UKR: 'Камерун',
      mensei_KSV: 'Kamerun',
    },
    {
      menseiID: 'CN',
      mensei_TR: 'Çin',
      mensei_EN: 'China',
      mensei_MK: 'Кина',
      mensei_UKR: 'Китай',
      mensei_KSV: 'Kina',
    },
    {
      menseiID: 'CO',
      mensei_TR: 'Kolombiya',
      mensei_EN: 'Colombia',
      mensei_MK: 'Колумбија',
      mensei_UKR: 'Колумбія',
      mensei_KSV: 'Kolumbia',
    },
    {
      menseiID: 'CR',
      mensei_TR: 'Kosta Rika',
      mensei_EN: 'Costa Rica',
      mensei_MK: 'Костарика',
      mensei_UKR: 'Коста-Ріка',
      mensei_KSV: 'Kosta Rika',
    },
    {
      menseiID: 'CS',
      mensei_TR: 'Sırb.ve Karadağ',
      mensei_EN: 'Serbia and Montenegro',
      mensei_MK: 'Србија и Црна Гора',
      mensei_UKR: 'Сербія та Чорногорія',
      mensei_KSV: 'Serbia dhe Mali i Zi',
    },
    {
      menseiID: 'CU',
      mensei_TR: 'Küba',
      mensei_EN: 'Cuba',
      mensei_MK: 'Куба',
      mensei_UKR: 'Куба',
      mensei_KSV: 'Kuba',
    },
    {
      menseiID: 'CV',
      mensei_TR: 'Cabo Verde',
      mensei_EN: 'Cabo Verde',
      mensei_MK: 'Кабо Верде',
      mensei_UKR: 'Кабо-Верде',
      mensei_KSV: 'Cabo Verde',
    },
    {
      menseiID: 'CX',
      mensei_TR: 'Christmas Adası',
      mensei_EN: 'Christmas Island',
      mensei_MK: 'Божиќен остров',
      mensei_UKR: 'Острів Різдва',
      mensei_KSV: 'Ishulli i Krishtlindjeve',
    },
    {
      menseiID: 'CY',
      mensei_TR: 'Kıbrıs',
      mensei_EN: 'Cyprus',
      mensei_MK: 'Кипар',
      mensei_UKR: 'Кіпр',
      mensei_KSV: 'Qipro',
    },
    {
      menseiID: 'CZ',
      mensei_TR: 'Çek Cumhuriyeti',
      mensei_EN: 'Czech Republic',
      mensei_MK: 'Чешка република',
      mensei_UKR: 'Чеська Республіка',
      mensei_KSV: 'Republika Çeke',
    },
    {
      menseiID: 'DE',
      mensei_TR: 'Almanya',
      mensei_EN: 'Germany',
      mensei_MK: 'Германија',
      mensei_UKR: 'Німеччина',
      mensei_KSV: 'Gjermani',
    },
    {
      menseiID: 'DJ',
      mensei_TR: 'Cibuti',
      mensei_EN: 'Djibouti',
      mensei_MK: 'Djибути',
      mensei_UKR: 'Джибуті',
      mensei_KSV: 'Xhibuti',
    },
    {
      menseiID: 'DK',
      mensei_TR: 'Danimarka',
      mensei_EN: 'Denmark',
      mensei_MK: 'Данска',
      mensei_UKR: 'Данія',
      mensei_KSV: 'Danimarka',
    },
    {
      menseiID: 'DM',
      mensei_TR: 'Dominik',
      mensei_EN: 'Dominican',
      mensei_MK: 'Доминиканка',
      mensei_UKR: 'Домініканський',
      mensei_KSV: 'Dominikane',
    },
    {
      menseiID: 'DO',
      mensei_TR: 'Dominik Cum.',
      mensei_EN: 'Dominican Rep.',
      mensei_MK: 'Доминиканска реп.',
      mensei_UKR: 'Домініканська Республіка',
      mensei_KSV: 'Rep Dominikane',
    },
    {
      menseiID: 'DZ',
      mensei_TR: 'Cezayir',
      mensei_EN: 'Algeria',
      mensei_MK: 'Алжир',
      mensei_UKR: 'Алжир',
      mensei_KSV: 'Algjeria',
    },
    {
      menseiID: 'EC',
      mensei_TR: 'Ekvador',
      mensei_EN: 'Ecuador',
      mensei_MK: 'Еквадор',
      mensei_UKR: 'Еквадор',
      mensei_KSV: 'Ekuador',
    },
    {
      menseiID: 'EE',
      mensei_TR: 'Estonya',
      mensei_EN: 'Estonia',
      mensei_MK: 'Естонија',
      mensei_UKR: 'Естонія',
      mensei_KSV: 'Estonia',
    },
    {
      menseiID: 'EG',
      mensei_TR: 'Mısır',
      mensei_EN: 'Egypt',
      mensei_MK: 'Египет',
      mensei_UKR: 'Єгипет',
      mensei_KSV: 'Egjipti',
    },
    {
      menseiID: 'EH',
      mensei_TR: 'Batı Sahra',
      mensei_EN: 'Western sahra',
      mensei_MK: 'Западна сахра',
      mensei_UKR: 'Західна сахра',
      mensei_KSV: 'Sahra perëndimore',
    },
    {
      menseiID: 'ER',
      mensei_TR: 'Eritre',
      mensei_EN: 'Eritrea',
      mensei_MK: 'Еритреја',
      mensei_UKR: 'Еритрея',
      mensei_KSV: 'Eritrea',
    },
    {
      menseiID: 'ES',
      mensei_TR: 'İspanya',
      mensei_EN: 'Spain',
      mensei_MK: 'Шпанија',
      mensei_UKR: 'Іспанія',
      mensei_KSV: 'Spanja',
    },
    {
      menseiID: 'ET',
      mensei_TR: 'Etopya',
      mensei_EN: 'Ethopia',
      mensei_MK: 'Етопија',
      mensei_UKR: 'Етопія',
      mensei_KSV: 'Etopia',
    },
    {
      menseiID: 'EU',
      mensei_TR: 'Avrupa birliği',
      mensei_EN: 'European Union',
      mensei_MK: 'европска унија',
      mensei_UKR: 'Європейський Союз',
      mensei_KSV: 'Bashkimi Europian',
    },
    {
      menseiID: 'FI',
      mensei_TR: 'Finlandiya',
      mensei_EN: 'Finland',
      mensei_MK: 'Финска',
      mensei_UKR: 'Фінляндія',
      mensei_KSV: 'Finlanda',
    },
    {
      menseiID: 'FJ',
      mensei_TR: 'Fiji',
      mensei_EN: 'Fiji',
      mensei_MK: 'Фиџи',
      mensei_UKR: 'Фіджі',
      mensei_KSV: 'Fixhi',
    },
    {
      menseiID: 'FK',
      mensei_TR: 'Falkland Ada.',
      mensei_EN: 'Falkland Island.',
      mensei_MK: 'Остров Фокланд.',
      mensei_UKR: 'Острів Фолкленд.',
      mensei_KSV: 'Ishulli Falkland.',
    },
    {
      menseiID: 'FM',
      mensei_TR: 'Mikronezya',
      mensei_EN: 'Micronesia',
      mensei_MK: 'Микронезија',
      mensei_UKR: 'Мікронезія',
      mensei_KSV: 'Mikronesia',
    },
    {
      menseiID: 'FO',
      mensei_TR: 'Faroe Adaları',
      mensei_EN: 'Faroe Islands',
      mensei_MK: 'Фарски острови',
      mensei_UKR: 'Фарерські острови',
      mensei_KSV: 'Ishujt Faroe',
    },
    {
      menseiID: 'FR',
      mensei_TR: 'Fransa',
      mensei_EN: 'France',
      mensei_MK: 'Франција',
      mensei_UKR: 'Франція',
      mensei_KSV: 'Franca',
    },
    {
      menseiID: 'GA',
      mensei_TR: 'Gabon',
      mensei_EN: 'Gabon',
      mensei_MK: 'Габон',
      mensei_UKR: 'Габон',
      mensei_KSV: 'Gabon',
    },
    {
      menseiID: 'GB',
      mensei_TR: 'Büyük Britanya',
      mensei_EN: 'Great Britain',
      mensei_MK: 'Велика Британија',
      mensei_UKR: 'Велика Британія',
      mensei_KSV: 'Britania e Madhe',
    },
    {
      menseiID: 'GD',
      mensei_TR: 'Grenada',
      mensei_EN: 'Grenada',
      mensei_MK: 'Гренада',
      mensei_UKR: 'Гренада',
      mensei_KSV: 'Grenada',
    },
    {
      menseiID: 'GE',
      mensei_TR: 'Gürcistan',
      mensei_EN: 'Georgia',
      mensei_MK: 'Georgiaорџија',
      mensei_UKR: 'Грузія',
      mensei_KSV: 'Gjeorgjia',
    },
    {
      menseiID: 'GF',
      mensei_TR: 'Frans.Guyanası',
      mensei_EN: 'Frans.Guana',
      mensei_MK: 'Франс.Гуана',
      mensei_UKR: 'Франс Гуана',
      mensei_KSV: 'Frans.Guana',
    },
    {
      menseiID: 'GH',
      mensei_TR: 'Gana',
      mensei_EN: 'Ghana',
      mensei_MK: 'Гана',
      mensei_UKR: 'Гана',
      mensei_KSV: 'Gana',
    },
    {
      menseiID: 'GI',
      mensei_TR: 'Cebelitarık',
      mensei_EN: 'Gibraltar',
      mensei_MK: 'Гибралтар',
      mensei_UKR: 'Гібралтар',
      mensei_KSV: 'Gjibraltar',
    },
    {
      menseiID: 'GL',
      mensei_TR: 'Grönland',
      mensei_EN: 'Greenland',
      mensei_MK: 'Гренланд',
      mensei_UKR: 'Гренландія',
      mensei_KSV: 'Grenlandë',
    },
    {
      menseiID: 'GM',
      mensei_TR: 'Gambia',
      mensei_EN: 'Gambia',
      mensei_MK: 'Гамбија',
      mensei_UKR: 'Гамбія',
      mensei_KSV: 'Gambia',
    },
    {
      menseiID: 'GN',
      mensei_TR: 'Gine',
      mensei_EN: 'Guinea',
      mensei_MK: 'Гвинеја',
      mensei_UKR: 'Гвінея',
      mensei_KSV: 'Guinea',
    },
    {
      menseiID: 'GP',
      mensei_TR: 'Guadeloupe',
      mensei_EN: 'Guadeloupe',
      mensei_MK: 'Гвадалупе',
      mensei_UKR: 'Гваделупа',
      mensei_KSV: 'Guadelupë',
    },
    {
      menseiID: 'GQ',
      mensei_TR: 'Ekvator Ginesi',
      mensei_EN: 'Equatorial Guinea',
      mensei_MK: 'Екваторијална Гвинеја',
      mensei_UKR: 'Екваторіальна Гвінея',
      mensei_KSV: 'Guinea Ekuatoriale',
    },
    {
      menseiID: 'GR',
      mensei_TR: 'Yunanistan',
      mensei_EN: 'Greece',
      mensei_MK: 'Грција',
      mensei_UKR: 'Греція',
      mensei_KSV: 'Greqia',
    },
    {
      menseiID: 'GS',
      mensei_TR: 'Güney Sandwich',
      mensei_EN: 'South Sandwich',
      mensei_MK: 'Јужен сендвич',
      mensei_UKR: 'Південний сендвіч',
      mensei_KSV: 'Sanduiç i Jugut',
    },
    {
      menseiID: 'GT',
      mensei_TR: 'Guatemala',
      mensei_EN: 'Guatemala',
      mensei_MK: 'Гватемала',
      mensei_UKR: 'Гватемала',
      mensei_KSV: 'Guatemala',
    },
    {
      menseiID: 'GU',
      mensei_TR: 'Guam',
      mensei_EN: 'Guam',
      mensei_MK: 'Гуам',
      mensei_UKR: 'Гуам',
      mensei_KSV: 'Guam',
    },
    {
      menseiID: 'GW',
      mensei_TR: 'Gine-Bissau',
      mensei_EN: 'Guinea-Bissau',
      mensei_MK: 'Гвинеја-Бисао',
      mensei_UKR: 'Гвінея-Бісау',
      mensei_KSV: 'Guinea-Bissau',
    },
    {
      menseiID: 'GY',
      mensei_TR: 'Guyana',
      mensei_EN: 'Guyana',
      mensei_MK: 'Гвајана',
      mensei_UKR: 'Гайана',
      mensei_KSV: 'Guajana',
    },
    {
      menseiID: 'HK',
      mensei_TR: 'Hong Kong',
      mensei_EN: 'Hong Kong',
      mensei_MK: 'Хонг Конг',
      mensei_UKR: 'Гонконг',
      mensei_KSV: 'Hong Kong',
    },
    {
      menseiID: 'HM',
      mensei_TR: 'Heard/McDon.Adl',
      mensei_EN: 'Heard / McDon.Adl',
      mensei_MK: 'Слушнале / Мекдон. Адл',
      mensei_UKR: 'Херд / Макдон. Адл',
      mensei_KSV: 'Heard / McDon.Adl',
    },
    {
      menseiID: 'HN',
      mensei_TR: 'Honduras',
      mensei_EN: 'Honduras',
      mensei_MK: 'Хондурас',
      mensei_UKR: 'Гондурас',
      mensei_KSV: 'Hondurasi',
    },
    {
      menseiID: 'HR',
      mensei_TR: 'Hırvatistan',
      mensei_EN: 'Croatia',
      mensei_MK: 'Хрватска',
      mensei_UKR: 'Хорватія',
      mensei_KSV: 'Kroacia',
    },
    {
      menseiID: 'HT',
      mensei_TR: 'Haiti',
      mensei_EN: 'Haiti',
      mensei_MK: 'Хаити',
      mensei_UKR: 'Гаїті',
      mensei_KSV: 'Haiti',
    },
    {
      menseiID: 'HU',
      mensei_TR: 'Macaristan',
      mensei_EN: 'Hungary',
      mensei_MK: 'Унгарија',
      mensei_UKR: 'Угорщина',
      mensei_KSV: 'Hungaria',
    },
    {
      menseiID: 'ID',
      mensei_TR: 'Endonezya',
      mensei_EN: 'Indonesia',
      mensei_MK: 'Индонезија',
      mensei_UKR: 'Індонезія',
      mensei_KSV: 'Indonezia',
    },
    {
      menseiID: 'IE',
      mensei_TR: 'İrlanda',
      mensei_EN: 'Ireland',
      mensei_MK: 'Ирска',
      mensei_UKR: 'Ірландія',
      mensei_KSV: 'Irlanda',
    },
    {
      menseiID: 'IK',
      mensei_TR: 'Irak-Yeni',
      mensei_EN: 'Iraq-New',
      mensei_MK: 'Ирак-Нов',
      mensei_UKR: 'Ірак-Новий',
      mensei_KSV: 'Irak-E Re',
    },
    {
      menseiID: 'IL',
      mensei_TR: 'İsrail',
      mensei_EN: 'Israel',
      mensei_MK: 'Израел',
      mensei_UKR: 'Ізраїль',
      mensei_KSV: 'Izraeli',
    },
    {
      menseiID: 'IN',
      mensei_TR: 'Hindistan',
      mensei_EN: 'India',
      mensei_MK: 'Индија',
      mensei_UKR: 'Індія',
      mensei_KSV: 'India',
    },
    {
      menseiID: 'IO',
      mensei_TR: 'İng.Hint Oky.T.',
      mensei_EN: 'Eng.Hint Oky.T.',
      mensei_MK: 'Инж. Хинт Оки.Т.',
      mensei_UKR: 'Підказка Oky.T.',
      mensei_KSV: 'Eng. Hint Oky.T.',
    },
    {
      menseiID: 'IQ',
      mensei_TR: 'Irak',
      mensei_EN: 'Iraq',
      mensei_MK: 'Ирак',
      mensei_UKR: 'Ірак',
      mensei_KSV: 'Irak',
    },
    {
      menseiID: 'IR',
      mensei_TR: 'İran',
      mensei_EN: 'Iranian',
      mensei_MK: 'Ирански',
      mensei_UKR: 'Іранський',
      mensei_KSV: 'Irani',
    },
    {
      menseiID: 'IS',
      mensei_TR: 'İzlanda',
      mensei_EN: 'Iceland',
      mensei_MK: 'Исланд',
      mensei_UKR: 'Ісландія',
      mensei_KSV: 'Islanda',
    },
    {
      menseiID: 'IT',
      mensei_TR: 'İtalya',
      mensei_EN: 'Italy',
      mensei_MK: 'Италија',
      mensei_UKR: 'Італія',
      mensei_KSV: 'Italia',
    },
    {
      menseiID: 'JM',
      mensei_TR: 'Jamaika',
      mensei_EN: 'Jamaica',
      mensei_MK: 'Јамајка',
      mensei_UKR: 'Ямайка',
      mensei_KSV: 'Xhamajka',
    },
    {
      menseiID: 'JO',
      mensei_TR: 'Ürdün',
      mensei_EN: 'Jordan',
      mensei_MK: 'Јордан',
      mensei_UKR: 'Йорданія',
      mensei_KSV: 'Jordania',
    },
    {
      menseiID: 'JP',
      mensei_TR: 'Japonya',
      mensei_EN: 'Japan',
      mensei_MK: 'Јапонија',
      mensei_UKR: 'Японія',
      mensei_KSV: 'Japonia',
    },
    {
      menseiID: 'KE',
      mensei_TR: 'Kenya',
      mensei_EN: 'Kenya',
      mensei_MK: 'Кенија',
      mensei_UKR: 'Кенія',
      mensei_KSV: 'Kenia',
    },
    {
      menseiID: 'KG',
      mensei_TR: 'Kırgızistan',
      mensei_EN: 'Kyrgyzstan',
      mensei_MK: 'Киргистан',
      mensei_UKR: 'Киргизстан',
      mensei_KSV: 'Kirgistani',
    },
    {
      menseiID: 'KH',
      mensei_TR: 'Kamboçya',
      mensei_EN: 'Cambodia',
      mensei_MK: 'Камбоџа',
      mensei_UKR: 'Камбоджа',
      mensei_KSV: 'Kamboxhia',
    },
    {
      menseiID: 'KI',
      mensei_TR: 'Kiribati',
      mensei_EN: 'Kiribati',
      mensei_MK: 'Кирибати',
      mensei_UKR: 'Кірібаті',
      mensei_KSV: 'Kiribati',
    },
    {
      menseiID: 'KM',
      mensei_TR: 'Komoro Adaları',
      mensei_EN: 'Comoro Islands',
      mensei_MK: 'Коморовски острови',
      mensei_UKR: 'Коморські острови',
      mensei_KSV: 'Ishujt Comoro',
    },
    {
      menseiID: 'KN',
      mensei_TR: 'St.Kitts&Nevis',
      mensei_EN: 'St. Kitts & Nevis',
      mensei_MK: 'Свети Китс и Невис',
      mensei_UKR: 'Сент-Кітс і Невіс',
      mensei_KSV: 'St. Kitts & Nevis',
    },
    {
      menseiID: 'KP',
      mensei_TR: 'Kuzey Kore',
      mensei_EN: 'North Korea',
      mensei_MK: 'Северна Кореа',
      mensei_UKR: 'Північна Корея',
      mensei_KSV: 'Korea e Veriut',
    },
    {
      menseiID: 'KR',
      mensei_TR: 'Güney Kore',
      mensei_EN: 'South Korea',
      mensei_MK: 'Јужна Кореа',
      mensei_UKR: 'Південна Корея',
      mensei_KSV: 'Korea e jugut',
    },
    {
      menseiID: 'KW',
      mensei_TR: 'Kuveyt',
      mensei_EN: 'Kuwait',
      mensei_MK: 'Кувајт',
      mensei_UKR: 'Кувейт',
      mensei_KSV: 'Kuvajti',
    },
    {
      menseiID: 'KY',
      mensei_TR: 'Cayman Adaları',
      mensei_EN: 'Cayman Islands',
      mensei_MK: 'Кајмански острови',
      mensei_UKR: 'Кайманові острови',
      mensei_KSV: 'Ishujt Kajman',
    },
    {
      menseiID: 'KZ',
      mensei_TR: 'Kazakistan',
      mensei_EN: 'Kazakhistan',
      mensei_MK: 'Казахстан',
      mensei_UKR: 'Казахстан',
      mensei_KSV: 'Kazakistani',
    },
    {
      menseiID: 'LA',
      mensei_TR: 'Laos',
      mensei_EN: 'Laos',
      mensei_MK: 'Лаос',
      mensei_UKR: 'Лаос',
      mensei_KSV: 'Laosi',
    },
    {
      menseiID: 'LB',
      mensei_TR: 'Lübnan',
      mensei_EN: 'Lebanon',
      mensei_MK: 'Либан',
      mensei_UKR: 'Ліван',
      mensei_KSV: 'Libani',
    },
    {
      menseiID: 'LC',
      mensei_TR: 'St. Lucia',
      mensei_EN: 'St. Lucia',
      mensei_MK: 'Св. Луција',
      mensei_UKR: 'Сент-Люсія',
      mensei_KSV: 'Shën Lucia',
    },
    {
      menseiID: 'LI',
      mensei_TR: 'Liechtenstein',
      mensei_EN: 'Liechtenstein',
      mensei_MK: 'Лихтенштајн',
      mensei_UKR: 'Ліхтенштейн',
      mensei_KSV: 'Lihtenshtajni',
    },
    {
      menseiID: 'LK',
      mensei_TR: 'Sri Lanka',
      mensei_EN: 'Sri lanka',
      mensei_MK: 'Шри Ланка',
      mensei_UKR: 'Шрі Ланка',
      mensei_KSV: 'Sri Lankë',
    },
    {
      menseiID: 'LR',
      mensei_TR: 'Liberya',
      mensei_EN: 'Liberia',
      mensei_MK: 'Либерија',
      mensei_UKR: 'Ліберія',
      mensei_KSV: 'Liberi',
    },
    {
      menseiID: 'LS',
      mensei_TR: 'Lesotho',
      mensei_EN: 'Lesotho',
      mensei_MK: 'Лесото',
      mensei_UKR: 'Лесото',
      mensei_KSV: 'Lesoto',
    },
    {
      menseiID: 'LT',
      mensei_TR: 'Litvanya',
      mensei_EN: 'Lithuania',
      mensei_MK: 'Литванија',
      mensei_UKR: 'Литва',
      mensei_KSV: 'Lituania',
    },
    {
      menseiID: 'LU',
      mensei_TR: 'Lüksemburg',
      mensei_EN: 'Luxembourg',
      mensei_MK: 'Луксембург',
      mensei_UKR: 'Люксембург',
      mensei_KSV: 'Luksemburgu',
    },
    {
      menseiID: 'LV',
      mensei_TR: 'Letonya',
      mensei_EN: 'Latvia',
      mensei_MK: 'Летонија',
      mensei_UKR: 'Латвія',
      mensei_KSV: 'Letonia',
    },
    {
      menseiID: 'LY',
      mensei_TR: 'Libya',
      mensei_EN: 'Libya',
      mensei_MK: 'Либија',
      mensei_UKR: 'Лівія',
      mensei_KSV: 'Libia',
    },
    {
      menseiID: 'MA',
      mensei_TR: 'Fas',
      mensei_EN: 'Morocco',
      mensei_MK: 'Мароко',
      mensei_UKR: 'Марокко',
      mensei_KSV: 'Maroku',
    },
    {
      menseiID: 'MC',
      mensei_TR: 'Monako',
      mensei_EN: 'Monaco',
      mensei_MK: 'Монако',
      mensei_UKR: 'Монако',
      mensei_KSV: 'Monako',
    },
    {
      menseiID: 'MD',
      mensei_TR: 'Moldova',
      mensei_EN: 'Moldova',
      mensei_MK: 'Молдавија',
      mensei_UKR: 'Молдова',
      mensei_KSV: 'Moldavia',
    },
    {
      menseiID: 'ME',
      mensei_TR: 'Karadağ',
      mensei_EN: 'Montenegro',
      mensei_MK: 'Црна Гора',
      mensei_UKR: 'Чорногорія',
      mensei_KSV: 'Mali i Zi',
    },
    {
      menseiID: 'MG',
      mensei_TR: 'Madagaskar',
      mensei_EN: 'Madagascar',
      mensei_MK: 'Мадагаскар',
      mensei_UKR: 'Мадагаскар',
      mensei_KSV: 'Madagaskar',
    },
    {
      menseiID: 'MH',
      mensei_TR: 'Marshall adalr.',
      mensei_EN: 'Marshall adalr.',
      mensei_MK: 'Маршал адалр.',
      mensei_UKR: 'Маршалл Адалр.',
      mensei_KSV: 'Marshall adalr.',
    },
    {
      menseiID: 'MK',
      mensei_TR: 'Makedonya',
      mensei_EN: 'Macedonia',
      mensei_MK: 'Македонија',
      mensei_UKR: 'Македонія',
      mensei_KSV: 'Maqedonia',
    },
    {
      menseiID: 'ML',
      mensei_TR: 'Mali',
      mensei_EN: 'Financial',
      mensei_MK: 'Финансиски',
      mensei_UKR: 'Фінансові',
      mensei_KSV: 'Financiare',
    },
    {
      menseiID: 'MM',
      mensei_TR: 'Myanmar',
      mensei_EN: 'Myanmar',
      mensei_MK: 'Мјанмар',
      mensei_UKR: "М'янма",
      mensei_KSV: 'Mianmar',
    },
    {
      menseiID: 'MN',
      mensei_TR: 'Moğolistan',
      mensei_EN: 'Mongolia',
      mensei_MK: 'Монголија',
      mensei_UKR: 'Монголія',
      mensei_KSV: 'Mongolia',
    },
    {
      menseiID: 'MO',
      mensei_TR: 'Macau',
      mensei_EN: 'Macau',
      mensei_MK: 'Макао',
      mensei_UKR: 'Макао',
      mensei_KSV: 'Makau',
    },
    {
      menseiID: 'MP',
      mensei_TR: 'Kz.Mariana Adl.',
      mensei_EN: 'Kz.Mariana Adl.',
      mensei_MK: 'Кз.Маријана Адл.',
      mensei_UKR: 'Kz.Mariana Adl.',
      mensei_KSV: 'Kz.Mariana Adl.',
    },
    {
      menseiID: 'MQ',
      mensei_TR: 'Martinik',
      mensei_EN: 'Martinique',
      mensei_MK: 'Мартиник',
      mensei_UKR: 'Мартініка',
      mensei_KSV: 'Martinique',
    },
    {
      menseiID: 'MR',
      mensei_TR: 'Moritanya',
      mensei_EN: 'Mauritania',
      mensei_MK: 'Мавританија',
      mensei_UKR: 'Мавританія',
      mensei_KSV: 'Mauritania',
    },
    {
      menseiID: 'MS',
      mensei_TR: 'Montserrat',
      mensei_EN: 'Montserrat',
      mensei_MK: 'Монтсерат',
      mensei_UKR: 'Монтсеррат',
      mensei_KSV: 'Montserrat',
    },
    {
      menseiID: 'MT',
      mensei_TR: 'Malta',
      mensei_EN: 'Malta',
      mensei_MK: 'Малта',
      mensei_UKR: 'Мальта',
      mensei_KSV: 'Maltë',
    },
    {
      menseiID: 'MU',
      mensei_TR: 'Mauritius',
      mensei_EN: 'Mauritius',
      mensei_MK: 'Маурициус',
      mensei_UKR: 'Маврикій',
      mensei_KSV: 'Mauritius',
    },
    {
      menseiID: 'MV',
      mensei_TR: 'Maldiv Adaları',
      mensei_EN: 'Maldive Islands',
      mensei_MK: 'Малдивски острови',
      mensei_UKR: 'Мальдівські острови',
      mensei_KSV: 'Ishujt Maldive',
    },
    {
      menseiID: 'MW',
      mensei_TR: 'Malavi',
      mensei_EN: 'Malawi',
      mensei_MK: 'Малави',
      mensei_UKR: 'Малаві',
      mensei_KSV: 'Malavi',
    },
    {
      menseiID: 'MX',
      mensei_TR: 'Meksika',
      mensei_EN: 'Mexican',
      mensei_MK: 'Мексиканец',
      mensei_UKR: 'Мексиканський',
      mensei_KSV: 'Meksika',
    },
    {
      menseiID: 'MY',
      mensei_TR: 'Malezya',
      mensei_EN: 'Malaysia',
      mensei_MK: 'Малезија',
      mensei_UKR: 'Малайзія',
      mensei_KSV: 'Malajzia',
    },
    {
      menseiID: 'MZ',
      mensei_TR: 'Mozambik',
      mensei_EN: 'Mozambique',
      mensei_MK: 'Мозамбик',
      mensei_UKR: 'Мозамбік',
      mensei_KSV: 'Mozambik',
    },
    {
      menseiID: 'NA',
      mensei_TR: 'Namibya',
      mensei_EN: 'Namibia',
      mensei_MK: 'Намибија',
      mensei_UKR: 'Намібія',
      mensei_KSV: 'Namibia',
    },
    {
      menseiID: 'NC',
      mensei_TR: 'Yeni Kaledonya',
      mensei_EN: 'New Caledonia',
      mensei_MK: 'Нова Каледонија',
      mensei_UKR: 'Нова Каледонія',
      mensei_KSV: 'Kaledonia e Re',
    },
    {
      menseiID: 'NE',
      mensei_TR: 'Nijer',
      mensei_EN: 'Niger',
      mensei_MK: 'Нигер',
      mensei_UKR: 'Нігер',
      mensei_KSV: 'Niger',
    },
    {
      menseiID: 'NF',
      mensei_TR: 'Norfolk Adaları',
      mensei_EN: 'Norfolk Islands',
      mensei_MK: 'Острови Норфолк',
      mensei_UKR: 'Острови Норфолк',
      mensei_KSV: 'Ishujt Norfolk',
    },
    {
      menseiID: 'NG',
      mensei_TR: 'Nijerya',
      mensei_EN: 'Nigeria',
      mensei_MK: 'Нигерија',
      mensei_UKR: 'Нігерія',
      mensei_KSV: 'Nigeria',
    },
    {
      menseiID: 'NI',
      mensei_TR: 'Nikaragua',
      mensei_EN: 'Nicaragua',
      mensei_MK: 'Никарагва',
      mensei_UKR: 'Нікарагуа',
      mensei_KSV: 'Nikaragua',
    },
    {
      menseiID: 'NL',
      mensei_TR: 'Hollanda',
      mensei_EN: 'Netherlands',
      mensei_MK: 'Холандија',
      mensei_UKR: 'Нідерланди',
      mensei_KSV: 'Holanda',
    },
    {
      menseiID: 'NO',
      mensei_TR: 'Norveç',
      mensei_EN: 'Norway',
      mensei_MK: 'Норвешка',
      mensei_UKR: 'Норвегія',
      mensei_KSV: 'Norvegjia',
    },
    {
      menseiID: 'NP',
      mensei_TR: 'Nepal',
      mensei_EN: 'Nepal',
      mensei_MK: 'Непал',
      mensei_UKR: 'Непал',
      mensei_KSV: 'Nepal',
    },
    {
      menseiID: 'NR',
      mensei_TR: 'Nauru',
      mensei_EN: 'Nauru',
      mensei_MK: 'Науру',
      mensei_UKR: 'Науру',
      mensei_KSV: 'Nauru',
    },
    {
      menseiID: 'NT',
      mensei_TR: 'NATO',
      mensei_EN: 'NATO',
      mensei_MK: 'НАТО',
      mensei_UKR: 'НАТО',
      mensei_KSV: 'NATO',
    },
    {
      menseiID: 'NU',
      mensei_TR: 'Niue Adaları',
      mensei_EN: 'Niue Islands',
      mensei_MK: 'Острови во Ниуе',
      mensei_UKR: 'Острови Ніуе',
      mensei_KSV: 'Ishujt Niue',
    },
    {
      menseiID: 'NZ',
      mensei_TR: 'Yeni Zelanda',
      mensei_EN: 'New Zeland',
      mensei_MK: 'Нов Зеланд',
      mensei_UKR: 'Нова Зеландія',
      mensei_KSV: 'Zelanda e Re',
    },
    {
      menseiID: 'OM',
      mensei_TR: 'Umman',
      mensei_EN: 'Oman',
      mensei_MK: 'Оман',
      mensei_UKR: 'Оман',
      mensei_KSV: 'Oman',
    },
    {
      menseiID: 'OR',
      mensei_TR: 'Turuncu',
      mensei_EN: 'Orange',
      mensei_MK: 'Портокалова',
      mensei_UKR: 'Помаранчевий',
      mensei_KSV: 'Portokalli',
    },
    {
      menseiID: 'PA',
      mensei_TR: 'Panama',
      mensei_EN: 'Panama',
      mensei_MK: 'Панама',
      mensei_UKR: 'Панама',
      mensei_KSV: 'Panama',
    },
    {
      menseiID: 'PE',
      mensei_TR: 'Peru',
      mensei_EN: 'Peru',
      mensei_MK: 'Перу',
      mensei_UKR: 'Перу',
      mensei_KSV: 'Peru',
    },
    {
      menseiID: 'PF',
      mensei_TR: 'Fr.Polonezyası',
      mensei_EN: 'Fr. Polynesia',
      mensei_MK: 'Отец Полинезија',
      mensei_UKR: 'О. Полінезія',
      mensei_KSV: 'Fr. Polinezia',
    },
    {
      menseiID: 'PG',
      mensei_TR: 'Papua Yeni Gine',
      mensei_EN: 'Papua New Guinea',
      mensei_MK: 'Папуа Нова Гвинеја',
      mensei_UKR: 'Папуа-Нова Гвінея',
      mensei_KSV: 'Papua Guinea e Re',
    },
    {
      menseiID: 'PH',
      mensei_TR: 'Filipinler',
      mensei_EN: 'Philippines',
      mensei_MK: 'Филипини',
      mensei_UKR: 'Філіппіни',
      mensei_KSV: 'Filipinet',
    },
    {
      menseiID: 'PK',
      mensei_TR: 'Pakistan',
      mensei_EN: 'Pakistan',
      mensei_MK: 'Пакистан',
      mensei_UKR: 'Пакистан',
      mensei_KSV: 'Pakistani',
    },
    {
      menseiID: 'VE',
      mensei_TR: 'Venezuela',
      mensei_EN: 'Venezuelan',
      mensei_MK: 'Венецуела',
      mensei_UKR: 'Венесуельський',
      mensei_KSV: 'Venezueliane',
    },
    {
      menseiID: 'VG',
      mensei_TR: 'İngz.Virgin Adl',
      mensei_EN: 'Engz.Virgin Adl',
      mensei_MK: 'Engz.Virgin Adl',
      mensei_UKR: 'Англ. Virgin adl',
      mensei_KSV: 'Engz.Virina Adl',
    },
    {
      menseiID: 'VI',
      mensei_TR: 'Virgin Adl(ABD)',
      mensei_EN: 'Virgin Adl (USA)',
      mensei_MK: 'Вирџин Адл (САД)',
      mensei_UKR: 'Вірджин Адл (США)',
      mensei_KSV: 'Virgin Adl (SHBA)',
    },
    {
      menseiID: 'VN',
      mensei_TR: 'Vietnam',
      mensei_EN: 'Vietnamese',
      mensei_MK: 'Виетнамски',
      mensei_UKR: 'В’єтнамські',
      mensei_KSV: 'Vietnami',
    },
    {
      menseiID: 'VU',
      mensei_TR: 'Vanuatu',
      mensei_EN: 'Vanuatu',
      mensei_MK: 'Вануату',
      mensei_UKR: 'Вануату',
      mensei_KSV: 'Vanuatu',
    },
    {
      menseiID: 'WF',
      mensei_TR: 'Wallis,Futuna',
      mensei_EN: 'Wallis, Futuna',
      mensei_MK: 'Валис, Футуна',
      mensei_UKR: 'Уолліс, Футуна',
      mensei_KSV: 'Wallis, Futuna',
    },
    {
      menseiID: 'WS',
      mensei_TR: 'Batı Samoa',
      mensei_EN: 'Western Samoa',
      mensei_MK: 'Западна Самоа',
      mensei_UKR: 'Західне Самоа',
      mensei_KSV: 'Samoa Perëndimore',
    },
    {
      menseiID: 'XK',
      mensei_TR: 'Kosova',
      mensei_EN: 'Kosovo',
      mensei_MK: 'Косово',
      mensei_UKR: 'Косово',
      mensei_KSV: 'Kosova',
    },
    {
      menseiID: 'XS',
      mensei_TR: 'Sırbistan',
      mensei_EN: 'Serbia',
      mensei_MK: 'Србија',
      mensei_UKR: 'Сербія',
      mensei_KSV: 'Serbia',
    },
    {
      menseiID: 'YE',
      mensei_TR: 'Yemen',
      mensei_EN: 'Yemen',
      mensei_MK: 'Јемен',
      mensei_UKR: 'Ємен',
      mensei_KSV: 'Jemeni',
    },
    {
      menseiID: 'YT',
      mensei_TR: 'Mayotte',
      mensei_EN: 'Mayotte',
      mensei_MK: 'Мајоте',
      mensei_UKR: 'Майотта',
      mensei_KSV: 'Mayotte',
    },
    {
      menseiID: 'ZA',
      mensei_TR: 'Güney Afrika',
      mensei_EN: 'South Africa',
      mensei_MK: 'Јужна Африка',
      mensei_UKR: 'Південна Африка',
      mensei_KSV: 'Afrika e Jugut',
    },
    {
      menseiID: 'ZM',
      mensei_TR: 'Zambia',
      mensei_EN: 'Zambia',
      mensei_MK: 'Замбија',
      mensei_UKR: 'Замбія',
      mensei_KSV: 'Zambia',
    },
    {
      menseiID: 'ZW',
      mensei_TR: 'Zimbabve',
      mensei_EN: 'Zimbabwe',
      mensei_MK: 'Зимбабве',
      mensei_UKR: 'Зімбабве',
      mensei_KSV: 'Zimbabve',
    },
  ],
};
